---

sudo: required

dist: trusty

language: generic

before_install:
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository -y ppa:fkrull/deadsnakes-python2.7
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get -y install ansible python2.7
  - ansible --version

insall:
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - ln -s ansible-role-docker ../docker

script:
  - sudo ansible-playbook tests/test.yml -i tests/hosts --syntax-check
  - sudo ansible-playbook tests/test.yml -i tests/hosts
  - sudo ansible-playbook tests/test.yml -i tests/hosts | grep -q 'unreachable=0.*failed=0' && exit 0 || exit 1

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
