---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: yum-config-manager --add-repo
  yum_repository:
    name: "{{ item.name | default(None) or omit }}"
    description: "{{ item.description | default(None) or omit }}"
    baseurl: "{{ item.baseurl | default(None) or omit }}"
    gpgcheck: "{{ item.gpgcheck | default(None) or omit }}"
    gpgkey: "{{ item.gpgkey | default(None) or omit }}"
    enabled: "{{ item.enabled | default(None) or omit }}"
    state: "{{ item.state | default(None) or omit }}"
  with_items: "{{ _yum_repository }}"
  notify: restart docker
  tags: docker

- name: yum install
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ _yum }}"
  notify: restart docker
  tags: docker
